spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: 6cfgl168lfnvmt841c9opve6m4
            clientSecret: 1djrqq5jo2g5nehd78t9de0e2dk31oo2pbroosbjmnbssveps3h5
            scope: openid, email, aws.cognito.signin.user.admin, phone
            redirectUriTemplate: https://school-tracker-pg12.co.uk/oauth2/idpresponse
            clientName: spring-boot
        provider:
          cognito:
            issuerUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_0WQ2XKQgq